[pytest]
markers =
    tc1: Test Case 1 - User Authentication
    tc2: Test Case 2 - Product Purchase Journey
    tc3: Test Case 3 - Multiple User Validation
    tc4: Test Case 4 - Browser Interaction Validation
addopts = -v --html=reports/execution_report.html --self-contained-html
log_cli = true
log_cli_level = INFO
